apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-7blm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus-7blm
    app.kubernetes.io/part-of: my-app-2
  name: devfile-sample-code-with-quarkus-7blm
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: devfile-sample-code-with-quarkus-7blm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: devfile-sample-code-with-quarkus-7blm
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/fduthill-tenant/my-app-2/devfile-sample-code-with-quarkus-7blm@sha256:40f4447b414196b69920415e125dd0ae9bf475ffe0021e2825244a90b9c2a196
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
